[package]
name = "fig"
version = "0.1.0"
authors = ["Claudio Matsuoka <cmatsuoka@gmail.com>"]

[lib]
name = "fig"
path = "src/fig/mod.rs"

[[bin]]
name = "rustlet"
path = "src/main.rs"
doc = false

[dependencies]
getopts = "0.2"

[profile.release]
lto = true
